name: CI

on:
  push:
    branches:
      - master
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
        HEROKU_API_KEY: ${{ secrets.heroku_api_key }}
        HEROKU_EMAIL: ${{ secrets.email }}
    - name: Add Heroku remote
      run: heroku git:remote --app $HEROKU_APP_NAME
      env:
        HEROKU_APP_NAME: "whateverb0t"
    - name: Push to Heroku
      run: git push heroku HEAD:master
